name: illegal_litter_detector
description: Illegal Littering Detector with Live & Local modes.
version: 2.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Networking
  http: ^1.2.0
  # State Management
  provider: ^6.1.1
  # Storage & Files
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  # Utilities
  intl: ^0.19.0
  permission_handler: ^11.3.0
  # Fonts
  google_fonts: ^6.1.0
  # Notifications
  flutter_local_notifications: ^17.0.0
  audioplayers: ^6.0.0
  # UI Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
